// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TekstilTakipSistemiCore.DATA.Context;

namespace TekstilTakipSistemiCore.DATA.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20230621111846_newDbCreated")]
    partial class newDbCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.Kimliklendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("EtiketNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("HasarAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MefrusatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MefrusatId");

                    b.ToTable("Kimliklendirmeler");
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.KirliDepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("CamasirKirliMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("HasarDurumu")
                        .HasColumnType("int");

                    b.Property<bool>("HurdaMi")
                        .HasColumnType("bit");

                    b.Property<int>("KimliklendirmeId")
                        .HasColumnType("int");

                    b.Property<int>("KirlenmeSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("KullanimdaMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TartimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeslimDurumu")
                        .HasColumnType("int");

                    b.Property<long>("YipranmaAgirligi")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("KirliDepolari");
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.Mefrusat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("MefrusatKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MefrusatTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Mefrusatlar");
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.PaketAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KimliklendirmeId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MefrusatId")
                        .HasColumnType("int");

                    b.Property<string>("OdaNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaketNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YikanmaSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaketAlanlari");
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.TemizDepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("AmbalajlandiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("BohcalandiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("CamasirYikandiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KimliklendirmeId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TartimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeslimDurumu")
                        .HasColumnType("int");

                    b.Property<int>("YikamaDurumu")
                        .HasColumnType("int");

                    b.Property<int>("YikanmaSayisi")
                        .HasColumnType("int");

                    b.Property<long>("YipranmaAgirligi")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TemizDepolari");
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.UygulamaKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UygulamaKullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            AktifMi = true,
                            GuncellemeZamani = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "admin.admin",
                            OlusturmaZamani = new DateTime(2023, 6, 21, 14, 18, 46, 290, DateTimeKind.Local).AddTicks(2423),
                            Sifre = "123",
                            Soyad = "Admin"
                        });
                });

            modelBuilder.Entity("TekstilTakipSistemiCore.DAL.Entities.Kimliklendirme", b =>
                {
                    b.HasOne("TekstilTakipSistemiCore.DAL.Entities.Mefrusat", "Mefrusat")
                        .WithMany("Kimliklendirmeler")
                        .HasForeignKey("MefrusatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
